### ISSUE TITLE
Mod settings not applying to autopsy table

### ISSUE THREAD

**Issue by rlancaster** [Heremeus/DissectionMod#1]
Mod settings aren't working on autopsy tables. Dissecting at an autopsy table yields approximately 600 xp and corpse destruction chances appear to be in the 90-95% range for pawns with 10+ medical skill (only one corpse survived on about 15-20 dissections for pawns with skill in the 10-12 range).  Changing the mod settings had no impact on either xp or the corpse destruction chance on an autopsy table, but did impact both if the procedure was performed on a dissection table in the same save.

(love the mod, btw!)

**Comment by Heremeus** [comment]
Thanks for the bug report! This should be fixed in the latest release (Version 2.2).

There was an issue if the autopsy table had bills to harvest organs and dissect corpses.
